Repository VDVde/OJP, pull requests merged in 2022-12, with the labels that each got.

#203 Rename ErrorMessage to Problem, split into specific types, revise output
  OJP/OJP_Common.xsd
  OJP/OJP_Fare.xsd
  OJP/OJP_FareSupport.xsd
  OJP/OJP_PlaceSupport.xsd
  OJP/OJP_Places.xsd
  OJP/OJP_RequestSupport.xsd
  OJP/OJP_StopEvents.xsd
  OJP/OJP_TripInfo.xsd
  OJP/OJP_Trips.xsd
  docs/generated/index.html
Labels: enhancement, documentation, to be disussed

#272 Add ReservationNeeded to DatedJourneyStructure
  OJP/OJP_JourneySupport.xsd
  docs/generated/index.html
Labels: enhancement, documentation

#286 Change order of attributes in WaitDuration to match other attributes
  OJP/OJP_Places.xsd
Labels: enhancement

#277 added ConsiderElevationData
  OJP/OJP_Trips.xsd
Labels: enhancement, documentation

#287 Consider elevation data in trip requests
  OJP/OJP_Trips.xsd
  docs/generated/index.html
Labels: enhancement, documentation

#282 Add TariffzoneFilter to TripDataFilterGroup
  OJP/OJP_Trips.xsd
  docs/generated/index.html
Labels: enhancement, documentation

#266 Improve documentation of PtModeFilter
  OJP/OJP_ModesSupport.xsd
  OJP/OJP_StopEvents.xsd
  OJP/OJP_Trips.xsd
  docs/generated/index.html
Labels: bug, documentation
