Repository VDVde/OJP, pull requests merged in 2023-06, with the labels that each got.

#375 Fix typos
  examples/linking_alps/LA_5T_TR_Request.xml
  examples/linking_alps/LA_LUR_TR_Request.xml
  examples/linking_alps/LA_LUR_TR_Response.xml
  examples/linking_alps/LA_STA_LIR_Request.xml
  examples/linking_alps/LA_STA_TR_Request.xml
Labels: bug

#376 Examples 4: LA MPTR, EU Spirit examples adapted to 2.0
  examples/eu_spirit/2023.06.16.eus.ojp.ep.request.xml
  examples/eu_spirit/2023.06.16.eus.ojp.ep.response.xml
  examples/eu_spirit/2023.06.16.eus.ojp.li.request.xml
  examples/eu_spirit/2023.06.16.eus.ojp.li.response.xml
  examples/eu_spirit/2023.06.16.eus.ojp.mptr.request.xml
  examples/eu_spirit/2023.06.16.eus.ojp.mptr.response.xml
  examples/eu_spirit/2023.06.16.eus.ojp.se.request.xml
  examples/eu_spirit/2023.06.16.eus.ojp.se.response.xml
  examples/eu_spirit/2023.06.16.eus.ojp.t.request.xml
  examples/eu_spirit/2023.06.16.eus.ojp.t.response.xml
  examples/eu_spirit/2023.06.16.eus.ojp.ti.request.xml
  examples/eu_spirit/2023.06.16.eus.ojp.ti.response.xml
  examples/linking_alps/LA_SBB_MPTR_Request.xml
  examples/linking_alps/LA_SBB_MPTR_Response.xml
Labels: documentation

#371 Add number of available tickets per fare product
  OJP/OJP_FareSupport.xsd
  docs/generated/index.html
  examples/functions/fare/FareResponse.xml
Labels: enhancement, documentation

#367 Cardinality of ArrivalFormationAssignment
  OJP/OJP_JourneySupport.xsd
  docs/generated/index.html
Labels: bug, documentation

#370 Multiple BookingNotes
  OJP/OJP_FareSupport.xsd
  docs/generated/index.html
  examples/functions/fare/FareResponse.xml
Labels: enhancement, documentation

#372 Added Transmodel TRIP REQUEST.Flexibilitywindow
  OJP/OJP_JourneySupport.xsd
  OJP/OJP_Trips.xsd
  docs/generated/index.html
  examples/functions/trip/TR_01_request_Bern_Luzern_10_results_optimisation_fastest.xml
Labels: enhancement, documentation
