Repository VDVde/OJP, pull requests merged in 2023-08, with the labels that each got.

#391 OJP_Locations renaming
  OJP/OJP_Locations.xsd
  docs/generated/index.html
Labels: bug, doc updated

#389 updating PassengerCategory for Dogs, Bicycles (and some other things)
  OJP/OJP_FareSupport.xsd
  docs/generated/index.html
Labels: enhancement, documentation

#384 OJPTripChangeRequest - TripParams added
  OJP/OJP_Trips.xsd
  docs/generated/index.html
  examples/functions/trip_change/ChangeTripRequest.xml
  examples/functions/trip_change/ChangeTripResponse.xml
  examples/functions/trip_change/TripChange_001_Request_laterDeparture.xml
Labels: bug, documentation

#390 Undefined delay broken connection contract
  OJP/OJP_JourneySupport.xsd
  OJP/OJP_Trips.xsd
  docs/generated/index.html
  examples/functions/trip/TR_03_response_search_by_StopPointName_many_params.xml
  examples/functions/trip/TR_04_response_search_by_StopPlaceRef_many_params.xml
  siri/xsd/siri_model/siri_all_journeyModel.xsd
Labels: enhancement, documentation

#400 BookingId in FareResult
  OJP/OJP_FareSupport.xsd
  OJP/OJP_Trips.xsd
  docs/generated/index.html
  examples/functions/fare/FareResponse.xml
Labels: enhancement, doc updated
