Repository VDVde/OJP, pull requests merged in 2023-10, with the labels that each got.

#410 remove all CDATA from examples
  examples/linking_alps/LA_Active_TR_Response.xml
  examples/linking_alps/LA_STA_TR_Response.xml
Labels: bug

#413 definitions added to all requests and responses based on TM
  OJP/OJP_Requests.xsd
  docs/generated/index.html
Labels: documentation

#412 clarifying the usage of coord and addresses in the stop event service
  OJP/OJP_StopEvents.xsd
  docs/generated/index.html
Labels: documentation

#379 implementing MODES OF OPERATION from FU 44
  OJP/OJP_Common.xsd
  OJP/OJP_JourneySupport.xsd
  OJP/OJP_Locations.xsd
  OJP/OJP_ModesSupport.xsd
  OJP/OJP_PlaceSupport.xsd
  OJP/OJP_StopEvents.xsd
  OJP/OJP_Trips.xsd
  docs/generated/index.html
  examples/eu_spirit/2023.06.16.eus.ojp.mptr.response.xml
  examples/eu_spirit/2023.06.16.eus.ojp.se.response.xml
  examples/eu_spirit/2023.06.16.eus.ojp.t.response.xml
  examples/eu_spirit/2023.06.16.eus.ojp.ti.response.xml
  examples/functions/fare/FareRequest.xml
  examples/functions/multipoint/MultipointTrip_001_Request_PR_36_83_98_109_127.xml
  examples/functions/trip/TR_01_response_Bern_Luzern_10results_optimisation_fastest.xml
  examples/functions/trip/TR_02_response_geoposition_2_geoposition.xml
  examples/functions/trip/TR_02_response_geoposition_2_geoposition_1.xml
  examples/functions/trip/TR_03_response_search_by_StopPointName_many_params.xml
  examples/functions/trip/TR_06_response_private_sharing.xml
  examples/functions/trip/TR_07_response_Delemont_normal.xml
  examples/functions/trip/TR_07_response_Delemont_senior.xml
  examples/functions/trip/TR_08_response_dog.xml
  examples/functions/trip/TR_09_response_restricted_lines.xml
  examples/functions/trip/TR_10_request_filters.xml
  examples/functions/trip/TR_11_request_with_ItModeToCover.xml
  examples/functions/trip/TR_12_response_example_restricted_service.xml
  examples/functions/trip/TR_13_first_leg_car_and_parking_last_leg_walk_or_taxi_request.xml
  examples/functions/trip/TR_14_first_leg_car_and_no_parking_last_leg_walk_or_bike_known_stop_request.xml
  examples/functions/trip/TR_16_mode_filter_example_request.xml
  examples/functions/trip/TR_ParallelService_OeBB_right_with_remain_in_vehicle.xml
  examples/functions/trip_change/ChangeTripRequest.xml
  examples/functions/trip_change/ChangeTripResponse.xml
  examples/functions/trip_change/TripChange_001_Request_laterDeparture.xml
  examples/functions/trip_change/TripChange_001_Response_laterDeparture.xml
  examples/functions/triprefine/RefinementRequest.xml
  examples/functions/triprefine/RefinementResponse.xml
  examples/linking_alps/LA_5T_TR_Response.xml
  examples/linking_alps/LA_ARIA_TR_Response_with_error.xml
  examples/linking_alps/LA_Active_TR_Response.xml
  examples/linking_alps/LA_SBB_MPTR_Response.xml
  examples/linking_alps/LA_STA_TR_Response.xml
  examples/linking_alps/LA_VAO_TR_Response.xml
  siri/xsd/siri_model/siri_modes.xsd
Labels: enhancement, documentation, breaking

#419 updates in the definition of LEG and MODE
  OJP/OJP_ModesSupport.xsd
  OJP/OJP_StopEvents.xsd
  OJP/OJP_Trips.xsd
  docs/generated/index.html
Labels: documentation

#423 added JourneyRelations
  OJP/OJP_JourneySupport.xsd
  docs/generated/index.html
  examples/functions/trip_information/TIR_response_with_JourneyRelations.xml
Labels: enhancement, documentation

#426 Restricted lines & MultiPointTripRequest
  OJP/OJP_JourneySupport.xsd
  OJP/OJP_Trips.xsd
  docs/generated/index.html
  examples/functions/multipoint/MultipointTrip_002_Request_IncludeAllRest.xml
Labels: bug, documentation

#425 Missing type for IncludeAllRestrictedLines
  OJP/OJP_StopEvents.xsd
Labels: bug, documentation

#427 Moving HikingProfile and CyclingProfile out of TripContentFilter
  OJP/OJP_Trips.xsd
  docs/generated/index.html
  examples/functions/trip/TR_02_request_geoposition_2_geoposition.xml
  examples/functions/trip/TR_10_request_filters.xml
  examples/functions/trip/TR_11_request_with_ItModeToCover.xml
  examples/functions/trip_change/ChangeTripRequest.xml
  examples/functions/triprefine/RefinementRequest.xml
Labels: bug, documentation
