Repository VDVde/OJP, pull requests merged in 2023-11, with the labels that each got.

#420 privateLift better info
  OJP/OJP_ModesSupport.xsd
  docs/generated/index.html
  examples/functions/trip/TR_11_request_with_ItModeToCover.xml
  examples/functions/trip/TR_16_mode_filter_example_request.xml
Labels: documentation

#309 Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation, doc updated

#429 Open Street Map => OpenStreetMap
  OJP/OJP_PlaceSupport.xsd
  docs/generated/index.html
Labels: typo

#431 typos and consistency
  OJP/OJP_FareSupport.xsd
  OJP/OJP_JourneySupport.xsd
  OJP/OJP_Locations.xsd
  OJP/OJP_PlaceSupport.xsd
  OJP/OJP_StopEvents.xsd
  OJP/OJP_Trips.xsd
  docs/generated/index.html
Labels: documentation

#404 added mapping on service level between TM and OJP
  docs/transmodel_ojp_mapping/Mapping_OJP_TRANSMODEL_V3.0.xlsx
Labels: documentation, doc updated

#434 typos from proofreading
  CHANGELOG.md
  OJP/OJP_Availability.xsd
  OJP/OJP_Common.xsd
  OJP/OJP_Fare.xsd
  OJP/OJP_FareSupport.xsd
  OJP/OJP_JourneySupport.xsd
  OJP/OJP_Lines.xsd
  OJP/OJP_Locations.xsd
  OJP/OJP_ModesSupport.xsd
  OJP/OJP_PlaceSupport.xsd
  OJP/OJP_Requests.xsd
  OJP/OJP_StopEvents.xsd
  OJP/OJP_TripInfo.xsd
  OJP/OJP_Trips.xsd
  OJP/OJP_Utility.xsd
  docs/generated/index.html
  examples/functions/trip/TR_ParallelService_OeBB_wrong.xml
  examples/functions/trip_information/TIR_response_with_JourneyRelations.xml
  examples/functions/trip_information/TIR_response_with_formation.xml
Labels: documentation, doc updated
