Repository VDVde/OJP, pull requests merged in 2023-01, with the labels that each got.

#267 Rename FareProductCode to FareProductId
  OJP/OJP_FareSupport.xsd
  docs/generated/index.html
Labels: enhancement, documentation

#243 LineInformation Request and Response service
  OJP/OJP_All.xsd
  OJP/OJP_Common.xsd
  OJP/OJP_JourneySupport.xsd
  OJP/OJP_Lines.xsd
  OJP/OJP_Requests.xsd
  docs/generated/index.html
  docs/schema-collection.xml
  examples/functions/LineRequest.xml
  examples/functions/LineResponse.xml
Labels: enhancement, documentation

#281 added PlaceSortingGroup to PlaceParamStructure
  OJP/OJP_PlaceSupport.xsd
  OJP/OJP_Places.xsd
  docs/generated/index.html
Labels: enhancement, documentation

#271 Necessary low level elements for User Preferences
  OJP/OJP_Trips.xsd
  docs/generated/index.html
Labels: enhancement, documentation, to be disussed

#301 Add sorting options for places
  OJP/OJP_PlaceSupport.xsd
  OJP/OJP_Places.xsd
  docs/generated/index.html
Labels: enhancement, documentation

#268 Adding SituationFullRef to LIR and SER
  OJP/OJP_JourneySupport.xsd
  OJP/OJP_PlaceSupport.xsd
  OJP/OJP_SituationSupport.xsd
  OJP/OJP_StopEvents.xsd
  OJP/OJP_Trips.xsd
  docs/generated/index.html
Labels: enhancement, documentation

#265 Expanding PathGuidance
  OJP/OJP_Trips.xsd
  docs/generated/index.html
Labels: enhancement, documentation

#259 rebuild usage of realtime information
  OJP/OJP_JourneySupport.xsd
  OJP/OJP_StopEvents.xsd
  OJP/OJP_TripInfo.xsd
  OJP/OJP_Trips.xsd
  docs/generated/index.html
Labels: enhancement, documentation

#244 extensions MENTZ TimedLeg and ExchangePoint
  OJP/OJP_Common.xsd
  OJP/OJP_FareSupport.xsd
  OJP/OJP_PlaceSupport.xsd
  OJP/OJP_Places.xsd
  OJP/OJP_Trips.xsd
  docs/generated/index.html
Labels: enhancement, documentation

#220 Add operators to PlaceResultStructure and ResponseContext, allow multiple per ServiceGroup
  OJP/OJP_Common.xsd
  OJP/OJP_JourneySupport.xsd
  OJP/OJP_Places.xsd
  OJP/OJP_RequestSupport.xsd
  docs/generated/index.html
  examples/function/OJPAvailabilityRequest.xml
  examples/switzerland/Trip_001_Response.xml
Labels: enhancement, documentation

#238 Add AccessFeatureStatus on PathLink
  OJP/OJP_Trips.xsd
  docs/generated/index.html
Labels: enhancement, documentation

#232 Aligning BookingArrangements more closely with NeTEx
  OJP/OJP_FareSupport.xsd
  docs/generated/index.html
Labels: enhancement, documentation

#295 Rename ExchangePointsResult element
  OJP/OJP_PlaceSupport.xsd
  OJP/OJP_Places.xsd
  docs/generated/index.html
Labels: bug, documentation, to be disussed

#294 Obsolete code in OJP_RequestSupport.xsd
  OJP/OJP_RequestSupport.xsd
  docs/generated/index.html
Labels: question, documentation

#291 Switches for accessibility information
  OJP/OJP_JourneySupport.xsd
  docs/generated/index.html
Labels: enhancement, documentation

#280 Parking options
  OJP/OJP_ModesSupport.xsd
  OJP/OJP_PlaceSupport.xsd
  OJP/OJP_Places.xsd
  docs/generated/index.html
Labels: enhancement, documentation

#230 Rename TripLeg to Leg
  OJP/OJP_Fare.xsd
  OJP/OJP_FareSupport.xsd
  OJP/OJP_JourneySupport.xsd
  OJP/OJP_Trips.xsd
  docs/generated/index.html
  examples/switzerland/Trip_001_Response.xml
Labels: enhancement, documentation

#215 Simplify element names of IDs
  OJP/OJP_Common.xsd
  OJP/OJP_Fare.xsd
  OJP/OJP_StopEvents.xsd
  OJP/OJP_Trips.xsd
  docs/generated/index.html
  examples/switzerland/Trip_001_Response.xml
Labels: enhancement, documentation, breaking

#308 Add Problem element to LineInformationResponse
  OJP/OJP_Lines.xsd
  docs/generated/index.html
Labels: enhancement, documentation

#313 First fare examples
  examples/functions/fare/FareRequest.xml
  examples/functions/fare/FareResponse.xml
Labels: enhancement, documentation

#314 Path to xsd corrected in xml examples
  examples/functions/availability/AvailabilityRequest.xml
  examples/functions/availability/AvailabilityRequest_1.xml
  examples/functions/availability/AvailabilityRequest_2.xml
  examples/functions/availability/AvailabilityResponse notOK.xml
  examples/functions/availability/AvailabilityResponse_OK.xml
  examples/functions/line/LineRequest.xml
  examples/functions/line/LineResponse.xml
Labels: bug

#231 Switching back Place to Location
  OJP/OJP_All.xsd
  OJP/OJP_JourneySupport.xsd
  OJP/OJP_Locations.xsd
  OJP/OJP_PlaceSupport.xsd
  OJP/OJP_Requests.xsd
  OJP/OJP_StopEvents.xsd
  docs/generated/index.html
  docs/schema-collection.xml
  examples/switzerland/LocationInformation_001_Stop_PlaceRef_Request.xml
  examples/switzerland/LocationInformation_001_Stop_PlaceRef_Response.xml
  examples/switzerland/LocationInformation_002_Stop_InitialInput_Request.xml
  examples/switzerland/LocationInformation_002_Stop_InitialInput_Response.xml
  examples/switzerland/PlaceInformation_002_Stop_InitialInput_Response.xml
Labels: enhancement, documentation
