Repository VDVde/OJP, pull requests merged in 2023-03, with the labels that each got.

#325 Update OJP_Locations.xsd
  OJP/OJP_Locations.xsd
Labels: documentation

#322 Add context to AvailabilityDelivery
  OJP/OJP_Availability.xsd
  docs/generated/index.html
Labels: enhancement, documentation

#327 Added annotation for GeoPosition
  OJP/OJP_PlaceSupport.xsd
  docs/generated/index.html
Labels: documentation, doc updated

#326 IsAlternativeOption
  OJP/OJP_Trips.xsd
  docs/generated/index.html
Labels: enhancement, documentation

#333 Aligning MultiPointTripPolicyGroup with TripPolicyGroup
  OJP/OJP_JourneySupport.xsd
  OJP/OJP_Trips.xsd
  docs/generated/index.html
Labels: bug, documentation

#323 Add TripContext to TripFareRequest and MultiTripFareRequest
  OJP/OJP_Fare.xsd
  docs/generated/index.html
Labels: enhancement, documentation

#316 Coherent use of ObjectIdType
  OJP/OJP_Fare.xsd
  OJP/OJP_FareSupport.xsd
  docs/generated/index.html
Labels: bug, documentation

#337 Update LineInformation with AreaGeometry
  OJP/OJP_Lines.xsd
  docs/generated/index.html
Labels: enhancement, documentation

#345 Annotation to FareProductRef parameter
  OJP/OJP_Fare.xsd
  docs/generated/index.html
Labels: documentation

#344 Restructuring SustainabilityGroup
  OJP/OJP_Common.xsd
  docs/generated/index.html
Labels: documentation

#343 Fixing a typo in OJP_Lines.xsd
  OJP/OJP_Lines.xsd
  docs/generated/index.html
Labels: bug, documentation

#264 Minimal Occupancy/Capacity added
  OJP/OJP_JourneySupport.xsd
  docs/generated/index.html
  examples/functions/trip/TR_05_response_with_occupation.xml
Labels: enhancement, documentation
